name: todo_final
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hooks_riverpod: ^2.3.6
  http: ^0.13.6
  riverpod_annotation: ^2.1.1
  freezed_annotation: ^2.2.0
  functional_widget: ^0.10.1
  go_router: ^7.0.1
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^14.1.0
  webview_flutter: ^4.2.1
  flutter_web_auth_2: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  custom_lint: ^0.4.0
  riverpod_lint: ^1.3.2
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  freezed: ^2.3.4
  hive_generator: ^2.0.0

flutter:

  uses-material-design: true
